=== AI4WORK-Project/manufacturing-scheduler/configuration_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "operators": {
            "type": "integer",
            "description": "Number of packaging operators.",
            "minimum": 1
        },
        "drawer_capacities": {
            "type": "array",
            "description": "Drawer capacities by box type.",
            "items": {
                "type": "object",
                "properties": {
                    "box": {
                        "type": "string"
                    },
                    "capacity": {
                        "type": "integer",
                        "minimum": 1
                    }
                },
                "required": [
                    "box",
                    "capacity"
                ],
                "additionalProperties": false
            }
        },
        "replenish_duration": {
            "type": "integer",
            "description": "Duration of replenishment activities. All the replenishments have the same duration.",
            "minimum": 1
        },
        "box_construction_duration": {
            "type": "integer",
            "description": "Duration of box construction activities. All the box constructions have the same duration.",
            "minimum": 1
        },
        "box_filling_durations": {
            "type": "array",
            "description": "Filling durations for each box type. The duration depends on the box type.",
            "items": {
                "type": "object",
                "properties": {
                    "box": {
                        "type": "string"
                    },
                    "filling_duration": {
                        "type": "integer",
                        "minimum": 1
                    }
                },
                "required": [
                    "box",
                    "filling_duration"
                ],
                "additionalProperties": false
            }
        }
    },
    "required": [
        "operators",
        "drawer_capacities",
        "replenish_duration",
        "box_construction_duration",
        "box_filling_durations"
    ],
    "additionalProperties": false
}

=== AI4WORK-Project/manufacturing-scheduler/configuration2.json
{
    "operators": 2,
    "drawer_capacities": [
        {
            "box": "A",
            "capacity": 40
        },
        {
            "box": "B",
            "capacity": 40
        },
        {
            "box": "C",
            "capacity": 40
        },
        {
            "box": "D",
            "capacity": 40
        },
        {
            "box": "E",
            "capacity": 40
        },
        {
            "box": "F",
            "capacity": 40
        },
        {
            "box": "G",
            "capacity": 40
        },
        {
            "box": "H",
            "capacity": 40
        }
    ],
    "replenish_duration": 300,
    "box_construction_duration": 60,
    "box_filling_durations": [
        {
            "box": "A",
            "filling_duration": 120
        },
        {
            "box": "B",
            "filling_duration": 120
        },
        {
            "box": "C",
            "filling_duration": 120
        },
        {
            "box": "D",
            "filling_duration": 120
        },
        {
            "box": "E",
            "filling_duration": 120
        },
        {
            "box": "F",
            "filling_duration": 120
        },
        {
            "box": "G",
            "filling_duration": 120
        },
        {
            "box": "H",
            "filling_duration": 120
        }
    ]
}
